name: Bug Report
description: Create a report about incorrect or unhelpful behaviour.
labels: ["issue:bug 🐛"]
body:
  - type: markdown
    attributes:
      value: Please make sure to search our issues for similar bugs first! If bug has been reported already, react with a thumbs-up, and/or leave a comment providing further details.
  - type: textarea
    attributes:
      id: current
      label: Problem and impact
      description: What problem you're running into? What impact does it have on you / your event?
      placeholder: When trying to do ____, pretalx suddenly shows me an error saying "...".
  - type: textarea
    attributes:
      id: expected
      label: Expected behaviour
      description: Sometimes bugs are subtle and the expected behaviour may need some explanation. Leave empty if it's just "Don't be broken."
  - type: textarea
    attributes:
      id: reproduction
      label: Steps to reproduce
      description: "Please give as much context as possible: Are there any settings that impact this behaviour? Which stage is your event in?"
      placeholder: |
        1.
        2.
        3.
        4.
  - type: textarea
    attributes:
      id: screenshots
      label: Screenshots
      description: If possible, show screenshots of the problem.
  - type: input
    attributes:
      id: link
      label: Link
      description: Link to the page where the bug occurs
  - type: input
    attributes:
      id: browser
      label: Browser (software, desktop or mobile?) and version
      description: Leave empty for backend problems
  - type: input
    attributes:
      id: os
      label: Operating system, dependency versions
      description: Leave empty for frontend problems
  - type: input
    attributes:
      id: version
      label: Version
      description: The pretalx version in use. (Leave empty if unknown.)
